
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import head,retrieve,dialogadd,menu
import directory
from directory import App
from datetime import datetime
import re 
class Ui_add_2(object):
    def inchange(self):
        self.invalid_2.setText("")
    def check(self, email):
        regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'
        if(re.search(regex,email)):  
            return True
        else:  
            return False
    def ctrauto(self):
        if retrieve.disabletest()==False:
            if self.class_2.text()!="" and self.division.text()!="":
                if head.cteacherautomation(self.class_2.text().lower(),self.division.text().lower())==True:
                    self.cteacher.setText(head.ctr)
                    self.cteacher.setReadOnly(True)
                else:
                    self.cteacher.setReadOnly(False)
                    pass
            else:
                self.cteacher.setReadOnly(False)
                self.cteacher.setText("")
        else:
            self.cteacher.setReadOnly(False)
            pass
    def clearingall(self):
        self.name.setText("")
        self.adid.setText("")
        self.cteacher.setText("")
        self.address.setText("")
        self.phonenumber.setText("")
        self.emailid.setText("")
        self.class_2.setText("")
        self.division.setText("")
        self.dateEdit.setDateTime(QtCore.QDateTime.currentDateTime())
        self.invalid_2.setText("")
        self.invalid.setText("")        
    def browse1(self):
        self.window = QtWidgets.QMainWindow()
        obj1=App()
        self.invalid.setText(directory.y)
    def cancel1(self): 
        self.window = QtWidgets.QMainWindow()
        self.ui=menu.Ui_menu()
        self.ui.setupUi(self.window)
        self.window.show()
        self.add_2.hide()
    def onDateChanged(self, qDate):
        global ddd
        ddd=('{0}/{1}/{2}'.format(qDate.day(), qDate.month(), qDate.year()))
    def adding(self):
        adidd=self.adid.text
        ct=self.cteacher.text
        d=self.division.text
        n=self.name.text
        a=self.address.toPlainText
        c=self.class_2.text
        pe=self.phonenumber.text
        pnoo=self.phonenumber.text()
        pno=len(pnoo)
        e=self.emailid.text
        self.invalid.text
        xyz=('students',)
        name=self.name.text()
        name=name.strip()
        name=name.split(' ')
        name2=''
        for i in name:
            name2+=i
        cteacher=self.cteacher.text()
        cteacher=cteacher.strip()
        cteacher=cteacher.split(' ')
        cteacher2=''
        for i in cteacher:
            cteacher2+=i
        if head.databasecheckingforadd()==True:    
            if xyz in head.tables:
                q=retrieve.rtest()
                dddd=self.dateEdit.date()
                dddd=[dddd.day(),dddd.month(),dddd.year()]
                ddddd=[QtCore.QDate.currentDate().day(),QtCore.QDate.currentDate().month(),QtCore.QDate.currentDate().year()]
                if self.adid.text()!="" and self.name.text()!="" and pnoo!="" and self.address.toPlainText()!="" and self.class_2.text()!="" and self.division.text()!="" and self.phonenumber.text()!="" and self.emailid.text()!="" and self.cteacher.text()!="":
                    if len(self.adid.text())==4 and name2.isalpha()==True and pno in [10,11] and self.address.toPlainText()!="" and self.division.text().isalpha()==True and self.phonenumber.text().isdigit()==True and self.emailid.text()!="" and cteacher2.isalpha()==True:
                        if self.class_2.text().isdigit()==True or self.class_2.text().lower() in ['lkg','ukg']:
                            if dddd!=ddddd:
                                if self.check(self.emailid.text())==True:
                                    if self.adid.text().lower() not in q:
                                        if self.invalid.text()!="" and directory.x!="":                                                                                                                    
                                                head.add(self.adid.text().lower(),directory.x,self.name.text().lower(),str(ddd),self.class_2.text().lower(),self.cteacher.text().lower(),self.division.text().lower(),1,self.phonenumber.text(),self.emailid.text(),self.address.toPlainText().lower())
                                                retrieve.readBlobData(self.adid.text().lower())
                                                self.name.setText("")
                                                self.adid.setText("")
                                                self.cteacher.setText("")
                                                
                                                self.address.setText("")
                                                self.phonenumber.setText("")
                                                self.emailid.setText("")
                                                self.class_2.setText("")
                                                self.division.setText("")
                                                self.dateEdit.setDateTime(QtCore.QDateTime.currentDateTime())
                                                self.invalid_2.setText("")
                                                self.invalid.setText("")
                                                
                                                self.window = QtWidgets.QMainWindow()
                                                self.ui=dialogadd.Ui_dialogadd()
                                                self.ui.setupUi(self.window)
                                                self.window.show()
                                                self.add_2.hide()
                                        elif self.invalid.text()=="" or directory.x=="":
                                                head.add(self.adid.text().lower(),"PHOTO NOT AVAILABLE",self.name.text().lower(),str(ddd),self.class_2.text().lower(),self.cteacher.text().lower(),self.division.text().lower(),1,self.phonenumber.text(),self.emailid.text(),self.address.toPlainText().lower())
                                                retrieve.readBlobData(self.adid.text().lower())
                                                self.name.setText("")
                                                self.adid.setText("")
                                                self.cteacher.setText("")
                                                
                                                self.address.setText("")
                                                self.phonenumber.setText("")
                                                self.emailid.setText("")
                                                self.class_2.setText("")
                                                self.division.setText("")
                                                self.dateEdit.setDateTime(QtCore.QDateTime.currentDateTime())
                                                self.invalid_2.setText("")
                                                self.invalid.setText("")
                                                
                                                self.window = QtWidgets.QMainWindow()
                                                self.ui=dialogadd.Ui_dialogadd()
                                                self.ui.setupUi(self.window)
                                                self.window.show()
                                                self.add_2.hide()
                                    elif self.adid.text().lower() in q:
                                            self.invalid_2.setText("Admission ID already exists")                                       
                                else:
                                    self.invalid_2.setText("Invalid Email ID")
                            else:
                                self.invalid_2.setText("All fields are mandatory")
                        else:
                            self.invalid_2.setText("Invalid Entry")                        
                    else:
                        self.invalid_2.setText("Invalid Entry")
                else:
                    self.invalid_2.setText("All fields are mandatory")        
            else:
                dddd=self.dateEdit.date()
                dddd=[dddd.day(),dddd.month(),dddd.year()]
                ddddd=[QtCore.QDate.currentDate().day(),QtCore.QDate.currentDate().month(),QtCore.QDate.currentDate().year()]
                if self.adid.text()!="" and self.name.text()!="" and pnoo!="" and self.address.toPlainText()!="" and self.class_2.text()!="" and self.division.text()!="" and self.phonenumber.text()!="" and self.emailid.text()!="" and self.cteacher.text()!="":
                   if len(self.adid.text())==4 and name2.isalpha()==True and pno in [10,11] and self.address.toPlainText()!="" and self.division.text().isalpha()==True and self.phonenumber.text().isdigit()==True and self.emailid.text()!="" and cteacher2.isalpha()==True:
                       if self.class_2.text().isdigit()==True or self.class_2.text().lower() in ['lkg','ukg']:
                            if dddd!=ddddd:
                                if self.check(self.emailid.text())==True:
                                    if self.invalid.text()!="" and directory.x!="":
                                            head.add(self.adid.text().lower(),directory.x,self.name.text().lower(),str(ddd),self.class_2.text().lower(),self.cteacher.text().lower(),self.division.text().lower(),1,self.phonenumber.text(),self.emailid.text(),self.address.toPlainText().lower())
                                            retrieve.readBlobData(self.adid.text().lower())
                                            self.name.setText("")
                                            self.adid.setText("")
                                            self.cteacher.setText("")  
                                            self.address.setText("")
                                            self.phonenumber.setText("")
                                            self.emailid.setText("")
                                            self.class_2.setText("")
                                            self.division.setText("")
                                            self.invalid_2.setText("")
                                            self.invalid.setText("")
                                            self.dateEdit.setDateTime(QtCore.QDateTime.currentDateTime())
                                            self.window = QtWidgets.QMainWindow()
                                            self.ui=dialogadd.Ui_dialogadd()
                                            self.ui.setupUi(self.window)
                                            self.window.show()
                                            self.add_2.hide()
                                    elif self.invalid.text()=="" or directory.x=="":
                                            head.add(self.adid.text().lower(),"PHOTO NOT AVAILABLE",self.name.text().lower(),str(ddd),self.class_2.text().lower(),self.cteacher.text().lower(),self.division.text().lower(),1,self.phonenumber.text(),self.emailid.text(),self.address.toPlainText().lower())
                                            retrieve.readBlobData(self.adid.text().lower())
                                            self.name.setText("")
                                            self.adid.setText("")
                                            self.cteacher.setText("")
                                            
                                            self.address.setText("")
                                            self.phonenumber.setText("")
                                            self.emailid.setText("")
                                            self.class_2.setText("")
                                            self.division.setText("")
                                            self.dateEdit.setDateTime(QtCore.QDateTime.currentDateTime())
                                            self.invalid_2.setText("")
                                            self.invalid.setText("")
                                            
                                            self.window = QtWidgets.QMainWindow()
                                            self.ui=dialogadd.Ui_dialogadd()
                                            self.ui.setupUi(self.window)
                                            self.window.show()
                                            self.add_2.hide()                                                        
                                else:
                                    self.invalid_2.setText("Invalid Email ID")
                            else:
                                self.invalid_2.setText("All fields are mandatory")
                       else:
                            self.invalid_2.setText("Invalid Entry")
                   else:
                        self.invalid_2.setText("Invalid Entry")
                else:
                    self.invalid_2.setText("All fields are mandatory")
        else:
            self.invalid_2.setText("Something went wrong")
    def setupUi(self, add_2):
        self.add_2=add_2
        add_2.setObjectName("add_2")
        add_2.resize(717, 531)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(add_2.sizePolicy().hasHeightForWidth())
        add_2.setSizePolicy(sizePolicy)
        add_2.setMinimumSize(QtCore.QSize(717, 531))
        add_2.setMaximumSize(QtCore.QSize(717, 531))
        self.centralwidget = QtWidgets.QWidget(add_2)
        self.centralwidget.setObjectName("centralwidget")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, -20, 751, 551))
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/ttt.jpg"))
        self.label.setObjectName("label")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(10, 10, 131, 41))
        font = QtGui.QFont()
        #self.add.setFocusPolicy(QtCore.Qt.NoFocus)
        font.setFamily("Palatino Linotype")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.add.setFont(font)
        self.add.setAcceptDrops(False)
        self.add.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.add.setCheckable(False)
        self.add.setDefault(True)
        self.add.setFlat(True)
        self.add.setObjectName("add")
        self.add.setFocusPolicy(QtCore.Qt.NoFocus)
        self.adid = QtWidgets.QLineEdit(self.centralwidget)
        self.adid.setGeometry(QtCore.QRect(291, 90, 231, 21))
        self.adid.setEnabled(True)
        font = QtGui.QFont()
        font.setPixelSize(14)
        self.adid.setFont(font)
        self.adid.setToolTip("")
        self.adid.setAccessibleName("")
        self.adid.setAutoFillBackground(False)
        self.adid.setStyleSheet("background:transparent;\n"
"")
        self.adid.setText("")
        self.adid.setFrame(True)
        self.adid.setDragEnabled(False)
        self.adid.setReadOnly(False)
        self.adid.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.adid.setClearButtonEnabled(False)
        self.adid.setObjectName("adid")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setEnabled(True)
        self.name.setGeometry(QtCore.QRect(291, 120, 231, 21))
        font = QtGui.QFont()
        font.setPixelSize(14)
        self.name.setFont(font)
        self.name.setToolTip("")
        self.name.setAccessibleName("")
        self.name.setAutoFillBackground(False)
        self.name.setStyleSheet("background:transparent;\n"
"")
        self.name.setText("")
        self.name.setFrame(True)
        self.name.setDragEnabled(False)
        self.name.setReadOnly(False)
        self.name.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.name.setClearButtonEnabled(False)
        self.name.setObjectName("name")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(291, 150, 91, 22))
        self.dateEdit.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.dateEdit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.dateEdit.setProperty("showGroupSeparator", False)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDateTime(QtCore.QDateTime.currentDateTime())
        self.class_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.class_2.setGeometry(QtCore.QRect(291, 180, 231, 21))
        font = QtGui.QFont()
        font.setPixelSize(14)
        self.class_2.setFont(font)
        self.class_2.setStyleSheet("background:transparent;\n"
"")
        self.class_2.setObjectName("class_2")
        self.division = QtWidgets.QLineEdit(self.centralwidget)
        self.division.setGeometry(QtCore.QRect(291, 210, 231, 21))
        font = QtGui.QFont()
        font.setPixelSize(14)
        self.division.setFont(font)
        self.division.setStyleSheet("\n"
"background:transparent;\n"
"")
        self.division.setText("")
        self.division.setFrame(True)
        self.division.setObjectName("division")
        self.cteacher = QtWidgets.QLineEdit(self.centralwidget)
        self.cteacher.setGeometry(QtCore.QRect(290, 240, 231, 21))
        font = QtGui.QFont()
        font.setPixelSize(14)
        self.cteacher.setFont(font)
        self.cteacher.setStyleSheet("\n"
"background:transparent;\n"
"")
        self.cteacher.setText("")
        self.cteacher.setFrame(True)
        self.cteacher.setObjectName("cteacher")

        self.photo = QtWidgets.QPushButton(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(291, 270, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.photo.setFont(font)
        self.photo.setAcceptDrops(False)
        self.photo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.photo.setCheckable(False)
        self.photo.setDefault(True)
        self.photo.setFlat(True)
        self.photo.setObjectName("photo")
        self.phonenumber = QtWidgets.QLineEdit(self.centralwidget)
        self.phonenumber.setGeometry(QtCore.QRect(290, 300, 231, 21))
        font = QtGui.QFont()
        font.setPixelSize(14)
        self.phonenumber.setFont(font)
        self.phonenumber.setStyleSheet("\n"
"background:transparent;\n"
"")
        self.phonenumber.setText("")
        self.phonenumber.setFrame(True)
        self.phonenumber.setObjectName("phonenumber")
        self.emailid = QtWidgets.QLineEdit(self.centralwidget)
        self.emailid.setGeometry(QtCore.QRect(291, 330, 231, 21))
        font = QtGui.QFont()
        font.setPixelSize(14)
        self.emailid.setFont(font)
        self.emailid.setStyleSheet("\n"
"background:transparent;\n"
"")
        self.emailid.setText("")
        self.emailid.setFrame(True)
        self.emailid.setObjectName("emailid")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 10, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/icon.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(650, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(171, 120, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(171, 360, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(171, 270, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(171, 210, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(171, 180, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(171, 120, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.address = QtWidgets.QTextEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(291, 360, 231, 91))
        font = QtGui.QFont()
        font.setPixelSize(14)
        self.address.setFont(font)
        self.address.setStyleSheet("background:transparent;\n"
"")
        self.address.setTabChangesFocus(True)
        self.address.setObjectName("address")
        
        
        
        
        self.invalid_2 = QtWidgets.QLabel(self.centralwidget)
        self.invalid_2.setGeometry(QtCore.QRect(291, 450, 159, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPixelSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.invalid_2.setFont(font)
        self.invalid_2.setStyleSheet("color:rgb(238, 0, 0)\n"
"")
        self.invalid_2.setText("")
        self.invalid_2.setObjectName("invalid_2")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(200, 470, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.submit.setFont(font)
        self.submit.setAcceptDrops(False)
        self.submit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.submit.setCheckable(False)
        self.submit.setDefault(True)
        self.submit.setFlat(True)
        self.submit.setObjectName("submit")        
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(320, 470, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancel.setFont(font)
        self.cancel.setAcceptDrops(False)
        self.cancel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cancel.setCheckable(False)
        self.cancel.setDefault(True)
        self.cancel.setFlat(True)
        self.cancel.setObjectName("cancel")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(441, 470, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clear.setFont(font)
        self.clear.setAcceptDrops(False)
        self.clear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.clear.setCheckable(False)
        self.clear.setDefault(True)
        self.clear.setFlat(True)
        self.clear.setObjectName("clear")
        
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(171, 300, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(171, 330, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(171, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(170, 240, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setTextFormat(QtCore.Qt.RichText)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_18.setObjectName("label_18")
        
        
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(171, 90, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        
        add_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(add_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 21))
        self.menubar.setObjectName("menubar")
        add_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(add_2)
        self.statusbar.setObjectName("statusbar")
        add_2.setStatusBar(self.statusbar)

        self.invalid = QtWidgets.QLabel(self.centralwidget)
        self.invalid.setGeometry(QtCore.QRect(380, 270, 275, 20))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.invalid.setFont(font)
        self.invalid.setStyleSheet("color: rgb(0, 0, 0);")
        self.invalid.setText("")
        
        self.invalid.setObjectName("invalid")

        self.retranslateUi(add_2)
        QtCore.QMetaObject.connectSlotsByName(add_2)
        
        self.adid.textChanged.connect(self.inchange)
        self.name.textChanged.connect(self.inchange)
        self.dateEdit.dateChanged.connect(self.inchange)
        self.class_2.textChanged.connect(self.inchange)
        self.division.textChanged.connect(self.inchange)
        self.cteacher.textChanged.connect(self.inchange)
        self.photo.clicked.connect(self.inchange)
        self.phonenumber.textChanged.connect(self.inchange)
        self.emailid.textChanged.connect(self.inchange)
        self.address.textChanged.connect(self.inchange)
        self.dateEdit.dateChanged.connect(self.onDateChanged)
        self.photo.clicked.connect(self.browse1)
        self.submit.clicked.connect(self.adding)
        self.cancel.clicked.connect(self.cancel1)
        self.clear.clicked.connect(self.clearingall)
        self.class_2.textChanged.connect(self.ctrauto)
        self.division.textChanged.connect(self.ctrauto)
    def retranslateUi(self, add_2):
        _translate = QtCore.QCoreApplication.translate
        add_2.setWindowTitle(_translate("add_2", "Add Student"))
        self.add.setText(_translate("add_2", "ADD"))
        self.label_3.setText(_translate("add_2", "admin"))
        self.label_4.setText(_translate("add_2", "NAME       "))
        self.label_10.setText(_translate("add_2", "ADDRESS"))
        self.label_11.setText(_translate("add_2", "PHOTO     "))
        self.label_12.setText(_translate("add_2", "DIVISION "))
        self.label_13.setText(_translate("add_2", "CLASS       "))
        self.address.setHtml(_translate("add_2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>"))
        self.submit.setText(_translate("add_2", "Submit"))
        self.cancel.setText(_translate("add_2", "Cancel"))
        self.clear.setText(_translate("add_2", "Clear All"))
        self.photo.setText(_translate("add_2", "Browse"))
        self.label_15.setText(_translate("add_2", "PHONE NO"))
        self.label_16.setText(_translate("add_2", "EMAIL ID"))
        self.label_17.setText(_translate("add_2", "D.O.B"))
        self.dateEdit.setDisplayFormat(_translate("add_2", "dd/MM/yyyy"))
        self.label_18.setText(_translate("add_2", "CLASS TEACHER"))
        self.label_5.setText(_translate("add_2", "ADMN NO"))
        
import pic


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_2 = QtWidgets.QMainWindow()
    ui = Ui_add_2()
    ui.setupUi(add_2)
    add_2.show()
    sys.exit(app.exec_())
