# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgetpassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import accountcheckforecho as ac
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector,head,createaccount
import createaccount as crtacc
from mysql.connector import Error
import first
class Ui_forgetpassword(object):
    def inchange(self):
        self.invalid.setText("")
    def backing1(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=createaccount.Ui_createaccount()
        self.ui.setupUi(self.window)
        self.window.show()
        self.forgetpassword0.hide()    
    def iconpass2(self):
        if ac.forecho22==1:
            self.showpd12.setStyleSheet("background-image: url(:/newPrefix/kisspng-computer-icons-cross-eye-5adf65cad344d8.0427956315245900268654 (1).png);")
            self.q2.setEchoMode(QtWidgets.QLineEdit.Normal)
            ac.forecho22=2
        else:
            self.showpd12.setStyleSheet("background-image: url(:/newPrefix/show-password-64 (1).png);")
            self.q2.setEchoMode(QtWidgets.QLineEdit.Password)
            ac.forecho22=1
    def checksub(self):
        if len(self.q1.text())!=0 and len(self.q2.text())!=0:
            head.createaccounting(head.uu,head.nnn,self.q1.text().lower(),self.q2.text().lower())
            self.window=QtWidgets.QMainWindow()
            self.ui=first.Ui_first()
            self.ui.setupUi(self.window)
            self.window.show()
            self.forgetpassword0.hide()            
        else:
            self.invalid.setText("All fields are mandatory")
    def setupUi(self, forgetpassword):
        self.forgetpassword0=forgetpassword
        forgetpassword.setObjectName("forgetpassword")
        forgetpassword.resize(719, 522)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(forgetpassword.sizePolicy().hasHeightForWidth())
        forgetpassword.setSizePolicy(sizePolicy)
        forgetpassword.setMinimumSize(QtCore.QSize(719, 522))
        forgetpassword.setMaximumSize(QtCore.QSize(719, 522))
        self.centralwidget = QtWidgets.QWidget(forgetpassword)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -30, 731, 571))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/White-Lock-Wallpaper-1080x2340-.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 200, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPixelSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 260, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPixelSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.q1 = QtWidgets.QLineEdit(self.centralwidget)
        self.q1.setGeometry(QtCore.QRect(145, 200, 300, 26))
        self.q1.setObjectName("q1")
        self.q1.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.q2 = QtWidgets.QLineEdit(self.centralwidget)
        self.q2.setGeometry(QtCore.QRect(145, 260, 300, 26))
        self.q2.setObjectName("q2")
        self.q2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.invalid = QtWidgets.QLabel(self.centralwidget)
        self.invalid.setGeometry(QtCore.QRect(145, 280, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPixelSize(13)
        self.invalid.setFont(font)
        self.invalid.setStyleSheet("color: rgb(255, 3, 3);")
        self.invalid.setText("")
        self.invalid.setObjectName("invalid")
        self.ok_ = QtWidgets.QPushButton(self.centralwidget)
        self.ok_.setGeometry(QtCore.QRect(280, 360, 75, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ok_.setFont(font)
        self.ok_.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ok_.setDefault(True)
        self.ok_.setFlat(True)
        self.ok_.setObjectName("ok_")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 50, 500, 100))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPixelSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ok_1 = QtWidgets.QPushButton(self.centralwidget)
        self.ok_1.setGeometry(QtCore.QRect(150, 360, 75, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ok_1.setFont(font)
        self.ok_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ok_1.setDefault(True)
        self.ok_1.setFlat(True)
        self.ok_1.setObjectName("ok_1")
        self.showpd12 = QtWidgets.QPushButton(self.centralwidget)
        self.showpd12.setGeometry(QtCore.QRect(458, 263, 22, 16))
        self.showpd12.setStyleSheet("background-image: url(:/newPrefix/show-password-64 (1).png);")
        self.showpd12.setText("")
        self.showpd12.setDefault(False)
        self.showpd12.setFlat(True)
        self.showpd12.setObjectName("showpd12")
        forgetpassword.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(forgetpassword)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 21))
        self.menubar.setObjectName("menubar")
        forgetpassword.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(forgetpassword)
        self.statusbar.setObjectName("statusbar")
        forgetpassword.setStatusBar(self.statusbar)
    
        self.showpd12.clicked.connect(self.iconpass2)
        self.retranslateUi(forgetpassword)
        QtCore.QMetaObject.connectSlotsByName(forgetpassword)
        self.ok_1.clicked.connect(self.checksub)
        self.ok_.clicked.connect(self.backing1)
        forgetpassword.setTabOrder(self.q1, self.q2)
        forgetpassword.setTabOrder(self.q2, self.ok_1)
        forgetpassword.setTabOrder(self.ok_1, self.ok_)
        self.q1.textChanged.connect(self.inchange)
        self.q2.textChanged.connect(self.inchange)
    def retranslateUi(self, forgetpassword):
        _translate = QtCore.QCoreApplication.translate
        forgetpassword.setWindowTitle(_translate("forgetpassword", "Create account"))
        self.label_2.setText(_translate("forgetpassword", "Question :"))
        self.label_3.setText(_translate("forgetpassword", "Answer    :"))
        self.ok_.setText(_translate("forgetpassword", "Back"))
        self.label_4.setText(_translate("forgetpassword", "Create question and answer for password recovery."))
        self.ok_1.setText(_translate("forgetpassword", "Submit"))
import pic


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    forgetpassword = QtWidgets.QMainWindow()
    ui = Ui_forgetpassword()
    ui.setupUi(forgetpassword)
    forgetpassword.show()
    sys.exit(app.exec_())
