# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changepassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import accountcheckforecho as fp
from PyQt5 import QtCore, QtGui, QtWidgets
import head,dialogpassword1,admin
import regex as re
class Ui_changepassword(object):
    def inchange(self):
        self.invalid.setText("")
    def back1(self):
        self.window = QtWidgets.QMainWindow()
        self.ui=admin.Ui_admin()
        self.ui.setupUi(self.window)
        self.window.show()
        self.changepassword.hide()
    def iconpass(self):
        if fp.forecho1==1:
            self.showpd.setStyleSheet("background-image: url(:/newPrefix/kisspng-computer-icons-cross-eye-5adf65cad344d8.0427956315245900268654 (1).png);")
            self.new_2.setEchoMode(QtWidgets.QLineEdit.Normal)
            fp.forecho1=2
        else:
            self.showpd.setStyleSheet("background-image: url(:/newPrefix/show-password-64 (1).png);")
            self.new_2.setEchoMode(QtWidgets.QLineEdit.Password)
            fp.forecho1=1
    def iconpass2(self):
        if fp.forechoo1==1:
            self.showpd_2.setStyleSheet("background-image: url(:/newPrefix/kisspng-computer-icons-cross-eye-5adf65cad344d8.0427956315245900268654 (1).png);")
            self.newconfirm.setEchoMode(QtWidgets.QLineEdit.Normal)
            fp.forechoo1=2
        else:
            self.showpd_2.setStyleSheet("background-image: url(:/newPrefix/show-password-64 (1).png);")
            self.newconfirm.setEchoMode(QtWidgets.QLineEdit.Password)
            fp.forechoo1=1
    def iconpass22(self):
        if fp.forechooo1==1:
            self.showpd_22.setStyleSheet("background-image: url(:/newPrefix/kisspng-computer-icons-cross-eye-5adf65cad344d8.0427956315245900268654 (1).png);")
            self.old.setEchoMode(QtWidgets.QLineEdit.Normal)
            fp.forechooo1=2
        else:
            self.showpd_22.setStyleSheet("background-image: url(:/newPrefix/show-password-64 (1).png);")
            self.old.setEchoMode(QtWidgets.QLineEdit.Password)
            fp.forechooo1=1
    def changing(self):
        if len(self.old.text())!=0 and len(self.new_2.text())!=0 and len(self.newconfirm.text())!=0:
            if head.changerr(str(self.old.text()),str(self.new_2.text()))==True:
                recheck = re.compile('[@_!#$%^&*()<>?/\|}{~:]')
                if len(self.new_2.text())>=8 and len(self.newconfirm.text())>=8:
                    if self.new_2.text()==self.newconfirm.text():
                        if(recheck.search(self.new_2.text()) == None):
                            self.invalid.setText("Minimum 1 special character required")
                        else:
                            head.changer(str(self.old.text()),str(self.new_2.text()))
                            self.window = QtWidgets.QMainWindow()
                            self.ui=dialogpassword1.Ui_dialogpassword()
                            self.ui.setupUi(self.window)
                            self.window.show()
                            self.changepassword.hide()
                            
                    else:
                        self.invalid.setText("Those passwords didn't match")
                else:
                    self.invalid.setText("Use 8 characters or more for your password")
            else:
                self.invalid.setText("Wrong password")
        else:
            self.invalid.setText("All fields are mandotary")
    def setupUi(self, changepassword):
        self.changepassword=changepassword
        changepassword.setObjectName("changepassword")
        changepassword.resize(719, 522)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(changepassword.sizePolicy().hasHeightForWidth())
        changepassword.setSizePolicy(sizePolicy)
        changepassword.setMinimumSize(QtCore.QSize(719, 522))
        changepassword.setMaximumSize(QtCore.QSize(719, 522))
        self.centralwidget = QtWidgets.QWidget(changepassword)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -30, 731, 571))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/White-Lock-Wallpaper-1080x2340-.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 140, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPixelSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 240, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPixelSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.old = QtWidgets.QLineEdit(self.centralwidget)
        self.old.setGeometry(QtCore.QRect(250, 140, 151, 21))
        self.old.setObjectName("old")
        self.old.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.new_2.setGeometry(QtCore.QRect(250, 240, 151, 21))
        self.new_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_2.setObjectName("new_2")
        self.invalid = QtWidgets.QLabel(self.centralwidget)
        self.invalid.setGeometry(QtCore.QRect(250, 310, 260, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPixelSize(13)
        self.invalid.setFont(font)
        self.invalid.setStyleSheet("color: rgb(255, 3, 3);")
        self.invalid.setText("")
        self.invalid.setObjectName("invalid")
        self.ok_ = QtWidgets.QPushButton(self.centralwidget)
        self.ok_.setGeometry(QtCore.QRect(250, 400, 75, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ok_.setFont(font)
        self.ok_.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ok_.setDefault(True)
        self.ok_.setFlat(True)
        self.ok_.setObjectName("ok_")
        self.newconfirm = QtWidgets.QLineEdit(self.centralwidget)
        self.newconfirm.setGeometry(QtCore.QRect(250, 290, 151, 21))
        self.newconfirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newconfirm.setObjectName("newconfirm")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 290, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPixelSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.showpd_22 = QtWidgets.QPushButton(self.centralwidget)
        self.showpd_22.setGeometry(QtCore.QRect(410, 143, 22, 16))
        self.showpd_22.setStyleSheet("background-image: url(:/newPrefix/show-password-64 (1).png);")
        self.showpd_22.setText("")
        self.showpd_22.setDefault(False)
        self.showpd_22.setFlat(True)
        self.showpd_22.setObjectName("showpd_2")
        self.showpd = QtWidgets.QPushButton(self.centralwidget)
        self.showpd.setGeometry(QtCore.QRect(410, 243, 22, 16))
        self.showpd.setStyleSheet("background-image: url(:/newPrefix/show-password-64 (1).png);")
        self.showpd.setText("")
        self.showpd.setDefault(False)
        self.showpd.setFlat(True)
        self.showpd.setObjectName("showpd")
        self.showpd_2 = QtWidgets.QPushButton(self.centralwidget)
        self.showpd_2.setGeometry(QtCore.QRect(410, 293, 22, 16))
        self.showpd_2.setStyleSheet("background-image: url(:/newPrefix/show-password-64 (1).png);")
        self.showpd_2.setText("")
        self.showpd_2.setDefault(False)
        self.showpd_2.setFlat(True)
        self.showpd_2.setObjectName("showpd_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(80, 190, 321, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.ok_1 = QtWidgets.QPushButton(self.centralwidget)
        self.ok_1.setGeometry(QtCore.QRect(250, 360, 75, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ok_1.setFont(font)
        self.ok_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ok_1.setDefault(True)
        self.ok_1.setFlat(True)
        self.ok_1.setObjectName("ok_1")
        changepassword.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(changepassword)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 21))
        self.menubar.setObjectName("menubar")
        changepassword.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(changepassword)
        self.statusbar.setObjectName("statusbar")
        changepassword.setStatusBar(self.statusbar)

        
        self.showpd.clicked.connect(self.iconpass)
        self.showpd_2.clicked.connect(self.iconpass2)
        self.showpd_22.clicked.connect(self.iconpass22)
        self.ok_.clicked.connect(self.back1)
        self.retranslateUi(changepassword)
        QtCore.QMetaObject.connectSlotsByName(changepassword)
        changepassword.setTabOrder(self.old, self.new_2)
        changepassword.setTabOrder(self.new_2,self.newconfirm)  
        changepassword.setTabOrder(self.newconfirm, self.ok_1)
        changepassword.setTabOrder(self.ok_1, self.ok_)
        changepassword.setTabOrder(self.ok_,self.showpd_22)
        changepassword.setTabOrder(self.showpd_22,self.showpd)
        changepassword.setTabOrder(self.showpd, self.showpd_2)
        
        self.ok_1.clicked.connect(self.changing)
        self.old.textChanged.connect(self.inchange)
        self.new_2.textChanged.connect(self.inchange)
        self.newconfirm.textChanged.connect(self.inchange)
    def retranslateUi(self, changepassword):
        _translate = QtCore.QCoreApplication.translate
        changepassword.setWindowTitle(_translate("changepassword", "Change password"))
        self.label_2.setText(_translate("changepassword", "OLD PASSWORD"))
        self.label_3.setText(_translate("changepassword", "NEW PASSWORD"))
        self.ok_.setText(_translate("changepassword", "Cancel"))
        self.label_4.setText(_translate("changepassword", "CONFIRM PASSWORD"))
        self.ok_1.setText(_translate("changepassword", "Submit"))
import pic


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    changepassword = QtWidgets.QMainWindow()
    ui = Ui_changepassword()
    ui.setupUi(changepassword)
    changepassword.show()
    sys.exit(app.exec_())
