# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogpromo.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import retrieve,promoteclass,promote,menu
class Ui_dialogpromo(object):
    def yesfor(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=promote.Ui_promote()
        self.ui.setupUi(self.window)
        self.window.show()
        self.dialogpromo.hide()
    def nofor(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=menu.Ui_menu()
        self.ui.setupUi(self.window)
        self.window.show()
        self.dialogpromo.hide()
    def setupUi(self, dialogpromo):
        self.dialogpromo=dialogpromo
        dialogpromo.setObjectName("dialogpromo")
        dialogpromo.resize(450, 185)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialogpromo.sizePolicy().hasHeightForWidth())
        dialogpromo.setSizePolicy(sizePolicy)
        dialogpromo.setMinimumSize(QtCore.QSize(450, 185))
        dialogpromo.setMaximumSize(QtCore.QSize(450, 185))
        self.label = QtWidgets.QLabel(dialogpromo)
        self.label.setGeometry(QtCore.QRect(-10, -10, 491, 261))
        self.label.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialogpromo)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 41, 41))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/hiclipart.com (3) (1).png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dialogpromo)
        self.label_3.setGeometry(QtCore.QRect(80, 50, 361, 41))
        font = QtGui.QFont()
        font.setPixelSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(48, 127, 255);\n"
"color: rgb(39, 96, 255);\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dialogpromo)
        self.label_4.setGeometry(QtCore.QRect(80, 20, 341, 41))
        font = QtGui.QFont()
        font.setPixelSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(48, 127, 255);\n"
"color: rgb(39, 96, 255);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(dialogpromo)
        self.label_5.setGeometry(QtCore.QRect(0, 140, 451, 51))
        self.label_5.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.yes = QtWidgets.QPushButton(dialogpromo)
        self.yes.setGeometry(QtCore.QRect(360, 150, 75, 23))
        self.yes.setAutoDefault(False)
        self.yes.setDefault(True)
        self.yes.setObjectName("yes")
        self.no = QtWidgets.QPushButton(dialogpromo)
        self.no.setGeometry(QtCore.QRect(270, 150, 75, 23))
        self.no.setStyleSheet("")
        self.no.setAutoDefault(True)
        self.no.setDefault(False)
        self.no.setFlat(False)
        self.no.setObjectName("no")
        self.yes.clicked.connect(self.yesfor)
        self.no.clicked.connect(self.nofor)
        self.retranslateUi(dialogpromo)
        QtCore.QMetaObject.connectSlotsByName(dialogpromo)
        dialogpromo.setTabOrder(self.yes, self.no)

    def retranslateUi(self, dialogpromo):
        _translate = QtCore.QCoreApplication.translate
        dialogpromo.setWindowTitle(_translate("dialogpromo", "Confirm"))
        self.label_3.setText(_translate("dialogpromo", "Do you want to continue ?"))
        self.label_4.setText(_translate("dialogpromo", "Promoted successfully."))
        self.yes.setText(_translate("dialogpromo", "Yes"))
        self.no.setText(_translate("dialogpromo", "No"))
import pic


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogpromo = QtWidgets.QDialog()
    ui = Ui_dialogpromo()
    ui.setupUi(dialogpromo)
    dialogpromo.show()
    sys.exit(app.exec_())
