# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgetpassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import head,admin
global forecho1,forechoo1
import accountcheckforecho as ac
forecho1=1
forechoo1=1
import changepasswordforget
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_forgetpassword(object):
    def questiongenerate(self):
        questionforlabel=head.question()
        qt=questionforlabel[0]
        if qt[-1]=='?':
            self.label_2.setText(questionforlabel[0])
        else:
            self.label_2.setText(questionforlabel[0]+'?')
    def inchange(self):
        self.invalid.setText("")
    def iconpass1(self):
        if ac.forecho21==1:
            self.showpd11.setStyleSheet("background-image: url(:/newPrefix/kisspng-computer-icons-cross-eye-5adf65cad344d8.0427956315245900268654 (1).png);")
            self.q2.setEchoMode(QtWidgets.QLineEdit.Normal)
            ac.forecho21=2
        else:
            self.showpd11.setStyleSheet("background-image: url(:/newPrefix/show-password-64 (1).png);")
            self.q2.setEchoMode(QtWidgets.QLineEdit.Password)
            ac.forecho21=1
    def back1(self):
        self.window = QtWidgets.QMainWindow()
        self.ui=admin.Ui_admin()
        self.ui.setupUi(self.window)
        self.window.show()
        self.forgetpassword.hide()
    def subb(self):
        if len(self.q2.text())!=0:
                if head.forgettt(self.q2.text().lower())==True:
                    head.forgett(self.q2.text().lower())
                    self.window = QtWidgets.QMainWindow()
                    self.ui=changepasswordforget.Ui_changepasswordforget()
                    self.ui.setupUi(self.window)
                    self.window.show()
                    self.forgetpassword.hide()
                else:
                    self.invalid.setText("Can't verify you are the admin")
        else:
            self.invalid.setText("The field is mandatory")
    def setupUi(self, forgetpassword):
        self.forgetpassword=forgetpassword
        forgetpassword.setObjectName("forgetpassword")
        forgetpassword.resize(719, 522)
        #forgetpassword.setTitle("Forget Password")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(forgetpassword.sizePolicy().hasHeightForWidth())
        forgetpassword.setSizePolicy(sizePolicy)
        forgetpassword.setMinimumSize(QtCore.QSize(719, 522))
        forgetpassword.setMaximumSize(QtCore.QSize(719, 522))
        self.centralwidget = QtWidgets.QWidget(forgetpassword)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -30, 731, 571))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/White-Lock-Wallpaper-1080x2340-.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 170, 1000, 50))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPixelSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
       
        self.q2 = QtWidgets.QLineEdit(self.centralwidget)
        self.q2.setGeometry(QtCore.QRect(120,215, 300, 30))
        self.q2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.q2.setObjectName("q2")
        self.invalid = QtWidgets.QLabel(self.centralwidget)
        self.invalid.setGeometry(QtCore.QRect(120, 250, 251, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPixelSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.invalid.setFont(font)
        self.invalid.setStyleSheet("color:rgb(238, 0, 0)\n"
"")

        self.invalid.setText("")
        self.invalid.setObjectName("invalid")
        self.ok_ = QtWidgets.QPushButton(self.centralwidget)
        self.ok_.setGeometry(QtCore.QRect(280, 360, 80, 26))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(50)
        self.ok_.setFont(font)
        self.ok_.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ok_.setDefault(True)
        self.ok_.setFlat(True)
        self.ok_.setObjectName("ok_")
        
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(50, 30, 500, 50))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPixelSize(17)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_4")
        self.label_41.setText("To continue, first verify that it's you")
        self.ok_1 = QtWidgets.QPushButton(self.centralwidget)
        self.ok_1.setGeometry(QtCore.QRect(150, 360, 80, 26))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(50)
        self.ok_1.setFont(font)
        self.ok_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ok_1.setDefault(True)
        self.ok_1.setFlat(True)
        self.ok_1.setObjectName("ok_1")
        
        self.showpd11 = QtWidgets.QPushButton(self.centralwidget)
        self.showpd11.setGeometry(QtCore.QRect(430, 218, 22, 16))
        self.showpd11.setStyleSheet("background-image: url(:/newPrefix/show-password-64 (1).png);")
        self.showpd11.setText("")
        self.showpd11.setDefault(False)
        self.showpd11.setFlat(True)
        self.showpd11.setObjectName("showpd11")
        
        forgetpassword.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(forgetpassword)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 21))
        self.menubar.setObjectName("menubar")
        forgetpassword.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(forgetpassword)
        self.statusbar.setObjectName("statusbar")
        self.questiongenerate()
        forgetpassword.setStatusBar(self.statusbar)
        self.showpd11.clicked.connect(self.iconpass1)
        self.retranslateUi(forgetpassword)
        QtCore.QMetaObject.connectSlotsByName(forgetpassword)
        forgetpassword.setTabOrder(self.q2, self.ok_1)
        forgetpassword.setTabOrder(self.ok_1, self.ok_)
        forgetpassword.setTabOrder(self.ok_, self.showpd11)
        self.ok_1.clicked.connect(self.subb)
        self.ok_.clicked.connect(self.back1)
        self.q2.textChanged.connect(self.inchange)
    def retranslateUi(self, forgetpassword):
        _translate = QtCore.QCoreApplication.translate
        forgetpassword.setWindowTitle(_translate("forgetpassword", "Forget password"))
        self.ok_.setText(_translate("forgetpassword", "BACK"))
        self.ok_1.setText(_translate("forgetpassword", "SUBMIT"))
import pic


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    forgetpassword = QtWidgets.QMainWindow()
    ui = Ui_forgetpassword()
    ui.setupUi(forgetpassword)
    forgetpassword.show()
    sys.exit(app.exec_())
