# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import view0g,first,retrieve

class Ui_gmenu(object):
    def disablebuttons(self):
        if retrieve.disabletest()==True: 
            self.view.setEnabled(False)
        else:
            self.view.setEnabled(True)
    def back1(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=first.Ui_first()
        self.ui.setupUi(self.window)
        self.window.show()
        self.gmenu.hide()
    def vie(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=view0g.Ui_view0()
        self.ui.setupUi(self.window)
        self.window.show()
        self.gmenu.hide()
    def setupUi(self, gmenu):
        self.gmenu=gmenu
        gmenu.setObjectName("gmenu")
        gmenu.resize(717, 531)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(gmenu.sizePolicy().hasHeightForWidth())
        gmenu.setSizePolicy(sizePolicy)
        gmenu.setMinimumSize(QtCore.QSize(717, 531))
        gmenu.setMaximumSize(QtCore.QSize(717, 531))
        self.centralwidget = QtWidgets.QWidget(gmenu)
        self.centralwidget.setObjectName("centralwidget")
        self.invalid = QtWidgets.QLabel(self.centralwidget)
        self.invalid.setGeometry(QtCore.QRect(150, 350, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.invalid.setFont(font)
        self.invalid.setStyleSheet("color: rgb(255, 3, 3);")
        self.invalid.setText("")
        self.invalid.setObjectName("invalid")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 751, 551))
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/student shaming.jpg"))
        self.label.setObjectName("label")
        self.view = QtWidgets.QPushButton(self.centralwidget)
        self.view.setGeometry(QtCore.QRect(290, 160, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.view.setFont(font)
        self.view.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view.setAutoDefault(False)
        self.view.setDefault(True)
        self.view.setFlat(True)
        self.view.setObjectName("view")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 10, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/icon.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(650, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(290, 300, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.exit.setDefault(True)
        self.exit.setFlat(True)
        self.exit.setObjectName("exit")
        gmenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(gmenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 21))
        self.menubar.setObjectName("menubar")
        gmenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(gmenu)
        self.statusbar.setObjectName("statusbar")
        gmenu.setStatusBar(self.statusbar)
        self.view.clicked.connect(self.vie)
        self.exit.clicked.connect(self.back1)
        self.retranslateUi(gmenu)
        QtCore.QMetaObject.connectSlotsByName(gmenu)
        self.disablebuttons()

    def retranslateUi(self, gmenu):
        _translate = QtCore.QCoreApplication.translate
        gmenu.setWindowTitle(_translate("gmenu", "Guest"))
        self.view.setText(_translate("gmenu", "VIEW"))
        self.label_3.setText(_translate("gmenu", "guest"))
        self.exit.setText(_translate("gmenu", "EXIT"))
import pic


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gmenu = QtWidgets.QMainWindow()
    ui = Ui_gmenu()
    ui.setupUi(gmenu)
    gmenu.show()
    sys.exit(app.exec_())
