# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mod2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import retrieve,modify2,mod1

class Ui_mod2(object):
    def inchange(self):
        self.invalid_3.setText("")
    def sub(self):
        yy=self.adid.text
        p=self.adid.text()
        if len(p)!=0:
            if len(p)==4:
                if retrieve.adidtest(p.lower())==True:
                    self.adid.setText("")
                    retrieve.readBlobData(p.lower())
                    
                    self.window=QtWidgets.QMainWindow()
                    self.ui=modify2.Ui_modify2()
                    self.ui.setupUi(self.window)
                    self.window.show()
                    self.mod2.hide()
                else:
                    self.invalid_3.setText("Student not Found")
            else:
                self.invalid_3.setText("Invalid Entry")
        else:
            self.invalid_3.setText("The field is mandatory")
            
    def can(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=mod1.Ui_mod1()
        self.ui.setupUi(self.window)
        self.window.show()
        self.mod2.hide()
    def setupUi(self, mod2):
        self.mod2=mod2
        mod2.setObjectName("mod2")
        mod2.resize(601, 354)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mod2.sizePolicy().hasHeightForWidth())
        mod2.setSizePolicy(sizePolicy)
        mod2.setMinimumSize(QtCore.QSize(601, 354))
        mod2.setMaximumSize(QtCore.QSize(601, 354))
        self.centralwidget = QtWidgets.QWidget(mod2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(-10, -20, 751, 541))
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/ttt.jpg"))
        self.label.setObjectName("label")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.add.setFont(font)
        self.add.setAcceptDrops(False)
        self.add.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.add.setCheckable(False)
        self.add.setDefault(True)
        self.add.setFlat(True)
        self.add.setObjectName("add")
        self.add.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 10, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/icon.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(530, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(140, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.adid = QtWidgets.QLineEdit(self.centralwidget)
        self.adid.setGeometry(QtCore.QRect(210, 150, 231, 21))
        self.adid.setStyleSheet("background:transparent")
        self.adid.setObjectName("adid")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(360, 200, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancel.setFont(font)
        self.cancel.setAcceptDrops(False)
        self.cancel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cancel.setCheckable(False)
        self.cancel.setDefault(True)
        self.cancel.setFlat(True)
        self.cancel.setObjectName("cancel")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(210, 200, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPixelSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.submit.setFont(font)
        self.submit.setAcceptDrops(False)
        self.submit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.submit.setCheckable(False)
        self.submit.setDefault(True)
        self.submit.setFlat(True)
        self.submit.setObjectName("submit")
        self.invalid_3 = QtWidgets.QLabel(self.centralwidget)
        self.invalid_3.setGeometry(QtCore.QRect(210, 170, 231, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPixelSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.invalid_3.setFont(font)
        self.invalid_3.setStyleSheet("color:rgb(238, 0, 0)\n"
"")
        self.invalid_3.setText("")
        self.invalid_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.invalid_3.setObjectName("invalid_3")
        mod2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mod2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 21))
        self.menubar.setObjectName("menubar")
        mod2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mod2)
        self.statusbar.setObjectName("statusbar")
        mod2.setStatusBar(self.statusbar)

        self.retranslateUi(mod2)
        QtCore.QMetaObject.connectSlotsByName(mod2)
        mod2.setTabOrder(self.adid, self.submit)
        mod2.setTabOrder(self.submit, self.cancel)
        mod2.setTabOrder(self.cancel, self.add)
        
        self.submit.clicked.connect(self.sub)
        self.cancel.clicked.connect(self.can)
        self.adid.textChanged.connect(self.inchange)
    def retranslateUi(self, mod2):
        _translate = QtCore.QCoreApplication.translate
        mod2.setWindowTitle(_translate("mod2", "Update"))
        self.add.setText(_translate("mod2", "UPDATE"))
        self.label_3.setText(_translate("mod2", "admin"))
        self.label_13.setText(_translate("mod2", "ADMN NO"))
        self.cancel.setText(_translate("mod2", "Back"))
        self.submit.setText(_translate("mod2", "Submit"))
import pic


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mod2 = QtWidgets.QMainWindow()
    ui = Ui_mod2()
    ui.setupUi(mod2)
    mod2.show()
    sys.exit(app.exec_())
