# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teeshowtest.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from mysql.connector import Error

class Ui_MainWindow(object):
    def connecttest(self):
        connection = mysql.connector.connect(host='localhost',user='admin',password='root',database='studentdirectory')
        cursor=connection.cursor()
        query="""select* from students"""
        cursor.execute(query)
        result=cursor.fetchall()
        connection.commit()
        connection.close()
        cursor.close()
        for row_number,row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number,column_data in enumerate(row_data):
                if column_number!=1:
                    item=str(column_data)
                    self.tableWidget.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(item))
                else:
                    item=self.getimage(column_data)
                    
                    self.tableWidget.setCellWidget(row_number,column_number,item)
        self.tableWidget.verticalHeader().setDefaultSectionSize(111)
        
        
        countc=self.tableWidget.columnCount
        print(countc)
    def getimage(self,image):
        imagelabel=QtWidgets.QLabel(self.centralwidget)
        imagelabel.setText("")
        imagelabel.setScaledContents(True)
        pixmap=QtGui.QPixmap()
        pixmap.loadFromData(image,'jpg')
        imagelabel.setPixmap(pixmap)
        return imagelabel
    def trial(self):
        self.tableWidget.clearContents()
        self.tableWidget.setRowCount(0)
        a=self.lineEdit.text
        connection = mysql.connector.connect(host='localhost',user='admin',password='root',database='studentdirectory')
        cursor=connection.cursor()
        b=str(self.lineEdit.text())
        b=b+'%'
        l=[]
        for i in b:
            l.append(i)
       
        l.append('"')
        l.insert(0,'"')
        print(l)
        c=""
        for i in l:
            c+=i     
        print(c)
        query="select * from students where name like "+str(c)
        print(query)
        cursor.execute(query)
        result=cursor.fetchall()
        connection.commit()
        connection.close()
        cursor.close()
        for row_number,row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number,column_data in enumerate(row_data):
                if column_number!=1:
                    item=str(column_data)
                    self.tableWidget.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(item))
                else:
                    item=self.getimage(column_data)
                    
                    self.tableWidget.setCellWidget(row_number,column_number,item)
        self.tableWidget.verticalHeader().setDefaultSectionSize(111)
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 781, 471))
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.show = QtWidgets.QPushButton(self.centralwidget)
        self.show.setGeometry(QtCore.QRect(300, 540, 75, 23))
        self.show.setObjectName("show")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 521, 21))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.connecttest()
        self.lineEdit.textChanged.connect(self.trial)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ADMN ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PHOTO"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ROLL  NO"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CLASS"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "DIVISION"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "CLASS TEACHER"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "D.O.B"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "EMAIL ID"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "PHONE NUMBER"))
        self.show.setText(_translate("MainWindow", "show"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
