# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewclass.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import retrieve
class Ui_viewclass(object):
    def classviewing(self):
        for row_number,row_data in enumerate(retrieve.result):
            self.tableView.insertRow(row_number)
            for column_number,column_data in enumerate(row_data):
                if column_number!=1:
                    item=str(column_data)
                    self.tableView.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(item))
                else:
                    item=self.getimage(column_data)
                    
                    self.tableView.setCellWidget(row_number,column_number,item)
        self.tableView.verticalHeader().setDefaultSectionSize(111)
        

        countc=self.tableView.columnCount
        print(countc)
    def getimage(self,image):
        imagelabel=QtWidgets.QLabel(self.centralwidget)
        imagelabel.setText("")
        imagelabel.setScaledContents(True)
        pixmap=QtGui.QPixmap()
        pixmap.loadFromData(image,'jpg')
        imagelabel.setPixmap(pixmap)
        return imagelabel
    def trial(self):
        self.tableWidget.clearContents()
        self.tableWidget.setRowCount(0)
        a=self.lineEdit.text
        connection = mysql.connector.connect(host='localhost',user='admin',password='root',database='studentdirectory')
        cursor=connection.cursor()
        b=str(self.lineEdit.text())
        b=b+'%'
        l=[]
        for i in b:
            l.append(i)
       
        l.append('"')
        l.insert(0,'"')
        print(l)
        c=""
        for i in l:
            c+=i     
        print(c)
        query="select * from students where name like "+str(c)
        print(query)
        cursor.execute(query)
        result=cursor.fetchall()
        connection.commit()
        connection.close()
        cursor.close()
        for row_number,row_data in enumerate(result):
            self.tableView.insertRow(row_number)
            for column_number,column_data in enumerate(row_data):
                if column_number!=1:
                    item=str(column_data)
                    self.tableView.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(item))
                else:
                    item=self.getimage(column_data)
                    
                    self.tableView.setCellWidget(row_number,column_number,item)
        self.tableView.verticalHeader().setDefaultSectionSize(111)

    def setupUi(self, viewclass):
        viewclass.setObjectName("viewclass")
        viewclass.resize(1339, 729)
        self.centralwidget = QtWidgets.QWidget(viewclass)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableWidget(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 160, 1301, 511))
        self.tableView.setStyleSheet("background:transparent;")
        self.tableView.setObjectName("tableView")
        self.tableView.setColumnCount(0)
        self.tableView.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1341, 711))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/ttt - Copy.jpg"))
        self.label.setObjectName("label")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(20, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add.setFont(font)
        self.add.setAcceptDrops(False)
        self.add.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.add.setCheckable(False)
        self.add.setDefault(True)
        self.add.setFlat(True)
        self.add.setObjectName("add")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1160, 60, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.classd = QtWidgets.QLabel(self.centralwidget)
        self.classd.setGeometry(QtCore.QRect(1230, 60, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.classd.setFont(font)
        self.classd.setText("")
        self.classd.setObjectName("classd")
        self.searching = QtWidgets.QLineEdit(self.centralwidget)
        self.searching.setGeometry(QtCore.QRect(20, 110, 341, 31))
        self.searching.setStyleSheet("background:transparent;\n"
"\n"
"")
        self.searching.setObjectName("searching")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 110, 47, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/sse.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1270, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1240, 10, 31, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/newPrefix/icon.png"))
        self.label_5.setObjectName("label_5")
        self.label.raise_()
        self.tableView.raise_()
        self.add.raise_()
        self.label_2.raise_()
        self.classd.raise_()
        self.searching.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        viewclass.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(viewclass)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1339, 21))
        self.menubar.setObjectName("menubar")
        viewclass.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(viewclass)
        self.statusbar.setObjectName("statusbar")
        viewclass.setStatusBar(self.statusbar)

        self.retranslateUi(viewclass)
        QtCore.QMetaObject.connectSlotsByName(viewclass)

    def retranslateUi(self, viewclass):
        _translate = QtCore.QCoreApplication.translate
        viewclass.setWindowTitle(_translate("viewclass", "MainWindow"))
        self.add.setText(_translate("viewclass", "SEARCH"))
        self.label_2.setText(_translate("viewclass", "CLASS :"))
        self.label_4.setText(_translate("viewclass", "admin"))
import pic


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    viewclass = QtWidgets.QMainWindow()
    ui = Ui_viewclass()
    ui.setupUi(viewclass)
    viewclass.show()
    sys.exit(app.exec_())
